/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesWebRouteImport } from './routes/services.web'
import { Route as ServicesUiuxRouteImport } from './routes/services.uiux'
import { Route as ServicesMobileRouteImport } from './routes/services.mobile'
import { Route as ServicesGameRouteImport } from './routes/services.game'
import { Route as ServicesCybersecurityRouteImport } from './routes/services.cybersecurity'
import { Route as ServicesCloudRouteImport } from './routes/services.cloud'
import { Route as ServicesAutomationRouteImport } from './routes/services.automation'
import { Route as ServicesAiRouteImport } from './routes/services.ai'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesWebRoute = ServicesWebRouteImport.update({
  id: '/web',
  path: '/web',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesUiuxRoute = ServicesUiuxRouteImport.update({
  id: '/uiux',
  path: '/uiux',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesMobileRoute = ServicesMobileRouteImport.update({
  id: '/mobile',
  path: '/mobile',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesGameRoute = ServicesGameRouteImport.update({
  id: '/game',
  path: '/game',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesCybersecurityRoute = ServicesCybersecurityRouteImport.update({
  id: '/cybersecurity',
  path: '/cybersecurity',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesCloudRoute = ServicesCloudRouteImport.update({
  id: '/cloud',
  path: '/cloud',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesAutomationRoute = ServicesAutomationRouteImport.update({
  id: '/automation',
  path: '/automation',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesAiRoute = ServicesAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => ServicesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/faq': typeof FaqRoute
  '/portfolio': typeof PortfolioRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRouteWithChildren
  '/terms': typeof TermsRoute
  '/services/ai': typeof ServicesAiRoute
  '/services/automation': typeof ServicesAutomationRoute
  '/services/cloud': typeof ServicesCloudRoute
  '/services/cybersecurity': typeof ServicesCybersecurityRoute
  '/services/game': typeof ServicesGameRoute
  '/services/mobile': typeof ServicesMobileRoute
  '/services/uiux': typeof ServicesUiuxRoute
  '/services/web': typeof ServicesWebRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/faq': typeof FaqRoute
  '/portfolio': typeof PortfolioRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/services/ai': typeof ServicesAiRoute
  '/services/automation': typeof ServicesAutomationRoute
  '/services/cloud': typeof ServicesCloudRoute
  '/services/cybersecurity': typeof ServicesCybersecurityRoute
  '/services/game': typeof ServicesGameRoute
  '/services/mobile': typeof ServicesMobileRoute
  '/services/uiux': typeof ServicesUiuxRoute
  '/services/web': typeof ServicesWebRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/faq': typeof FaqRoute
  '/portfolio': typeof PortfolioRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRouteWithChildren
  '/terms': typeof TermsRoute
  '/services/ai': typeof ServicesAiRoute
  '/services/automation': typeof ServicesAutomationRoute
  '/services/cloud': typeof ServicesCloudRoute
  '/services/cybersecurity': typeof ServicesCybersecurityRoute
  '/services/game': typeof ServicesGameRoute
  '/services/mobile': typeof ServicesMobileRoute
  '/services/uiux': typeof ServicesUiuxRoute
  '/services/web': typeof ServicesWebRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/blog'
    | '/careers'
    | '/contact'
    | '/dashboard'
    | '/faq'
    | '/portfolio'
    | '/pricing'
    | '/privacy'
    | '/services'
    | '/terms'
    | '/services/ai'
    | '/services/automation'
    | '/services/cloud'
    | '/services/cybersecurity'
    | '/services/game'
    | '/services/mobile'
    | '/services/uiux'
    | '/services/web'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/blog'
    | '/careers'
    | '/contact'
    | '/dashboard'
    | '/faq'
    | '/portfolio'
    | '/pricing'
    | '/privacy'
    | '/terms'
    | '/services/ai'
    | '/services/automation'
    | '/services/cloud'
    | '/services/cybersecurity'
    | '/services/game'
    | '/services/mobile'
    | '/services/uiux'
    | '/services/web'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/blog'
    | '/careers'
    | '/contact'
    | '/dashboard'
    | '/faq'
    | '/portfolio'
    | '/pricing'
    | '/privacy'
    | '/services'
    | '/terms'
    | '/services/ai'
    | '/services/automation'
    | '/services/cloud'
    | '/services/cybersecurity'
    | '/services/game'
    | '/services/mobile'
    | '/services/uiux'
    | '/services/web'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  BlogRoute: typeof BlogRoute
  CareersRoute: typeof CareersRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  FaqRoute: typeof FaqRoute
  PortfolioRoute: typeof PortfolioRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/web': {
      id: '/services/web'
      path: '/web'
      fullPath: '/services/web'
      preLoaderRoute: typeof ServicesWebRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/uiux': {
      id: '/services/uiux'
      path: '/uiux'
      fullPath: '/services/uiux'
      preLoaderRoute: typeof ServicesUiuxRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/mobile': {
      id: '/services/mobile'
      path: '/mobile'
      fullPath: '/services/mobile'
      preLoaderRoute: typeof ServicesMobileRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/game': {
      id: '/services/game'
      path: '/game'
      fullPath: '/services/game'
      preLoaderRoute: typeof ServicesGameRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/cybersecurity': {
      id: '/services/cybersecurity'
      path: '/cybersecurity'
      fullPath: '/services/cybersecurity'
      preLoaderRoute: typeof ServicesCybersecurityRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/cloud': {
      id: '/services/cloud'
      path: '/cloud'
      fullPath: '/services/cloud'
      preLoaderRoute: typeof ServicesCloudRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/automation': {
      id: '/services/automation'
      path: '/automation'
      fullPath: '/services/automation'
      preLoaderRoute: typeof ServicesAutomationRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/ai': {
      id: '/services/ai'
      path: '/ai'
      fullPath: '/services/ai'
      preLoaderRoute: typeof ServicesAiRouteImport
      parentRoute: typeof ServicesRoute
    }
  }
}

interface ServicesRouteChildren {
  ServicesAiRoute: typeof ServicesAiRoute
  ServicesAutomationRoute: typeof ServicesAutomationRoute
  ServicesCloudRoute: typeof ServicesCloudRoute
  ServicesCybersecurityRoute: typeof ServicesCybersecurityRoute
  ServicesGameRoute: typeof ServicesGameRoute
  ServicesMobileRoute: typeof ServicesMobileRoute
  ServicesUiuxRoute: typeof ServicesUiuxRoute
  ServicesWebRoute: typeof ServicesWebRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesAiRoute: ServicesAiRoute,
  ServicesAutomationRoute: ServicesAutomationRoute,
  ServicesCloudRoute: ServicesCloudRoute,
  ServicesCybersecurityRoute: ServicesCybersecurityRoute,
  ServicesGameRoute: ServicesGameRoute,
  ServicesMobileRoute: ServicesMobileRoute,
  ServicesUiuxRoute: ServicesUiuxRoute,
  ServicesWebRoute: ServicesWebRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  BlogRoute: BlogRoute,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  FaqRoute: FaqRoute,
  PortfolioRoute: PortfolioRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ServicesRoute: ServicesRouteWithChildren,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
